### ISSUE TITLE
[Aula 8] Instalação do `punkt` e inclusão do requirements.txt

### ISSUE THREAD

**Issue by adamesalles** [emap-nlp-2022/syllabus#24]
Estive rodando o notebook [aula-08/modelo-linguagem.ipynb](https://github.com/adamesalles/syllabus/blob/b25c01219868b22b570dfb5cdf42f9e19fbbc621/aula-08/modelo-linguagem.ipynb) e me deparei com o seguinte erro ao executar células utilizando o `nltk`:

```bash
LookupError: 
**********************************************************************
  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')
```

A solução é bem simples e o próprio erro o apresenta. Não sei se acontece somente comigo, mas acredito ser razoável de incluir essa linha ao importar o módulo.

Como já estou abrindo esse issue, aproveito para mencionar a inclusão do requirements.txt

**Comment by arademaker** [comment]
mas onde eu colocaria este código? Só se for no README com instruções para depois da instalação das libs... acho que cada um pode fazer a instalação dos dados necessários por cada lib. Com a http://spacy.io também precisamos baixar o modelo usando a lib..
