### ISSUE TITLE
[Aula 8] Contagem de unigrams no slide 21

### ISSUE THREAD

**Issue by cristianolarrea** [emap-nlp-2022/syllabus#27]
Conforme comentamos, estou abrindo esse issue para a discussão da contagem de unigramas no slide da aula 8. 
A contagem não inclui os marcadores de início e fim das sentenças (s e \s).
Por isso, creio que o correto seria incluir esses dois marcadores nos bullets e a contagem final de unigramas ser 9

![image](https://user-images.githubusercontent.com/70357148/186799225-b2cbe300-d79e-4fa0-96fd-1fd906e851d0.png)

**Comment by arademaker** [comment]
pensando um pouco, os slides estão corretos. Unigramas, por serem apenas um token, não precisam dos símbolos <s> e </s>. Note que não teria nunca problema de ter um token de uma sentença misturado com token de outra sentença... afinal, é apenas um token!
