### ISSUE TITLE
Mostrar os testes de n-gramas para diferentes valores de n

### ISSUE THREAD

**Issue by Rian-Freitas** [emap-nlp-2022/syllabus#37]
@arademaker , boa tarde.

Estou fazendo a 2 do assignment 3 e não sei qual seria a melhor maneira de mostrar testes diferentes no task-2.py.  Escolho o n que tiver melhor resultado para manter no arquivo?

**Comment by Rian-Freitas** [comment]
@wellington36

**Comment by wellington36** [comment]
A ideia é você ver o que acontece com cada n e dai escolher.
