### ISSUE TITLE
Lidstone com divisão por zero

### ISSUE THREAD

**Issue by Rian-Freitas** [emap-nlp-2022/syllabus#38]
@wellington36 eu não sei se isso ocorreu nos seus testes, mas estranhamente quando peço para o LM calcular a perplexidade usando Lidstone, ele dá erro de divisão por zero.

Você tem alguma ideia do porquê disso?

**Comment by Rian-Freitas** [comment]
![Image 2](https://user-images.githubusercontent.com/85463854/192155440-26b882c8-06f9-43c5-981a-7956c88f8fb4.png)

**Comment by Rian-Freitas** [comment]
![Image 3](https://user-images.githubusercontent.com/85463854/192155474-8c187634-4205-4494-a3d0-30dce8210b41.png)

**Comment by lfzinho** [comment]
Isso aconteceu comigo também. O problema é que a função `fit()` altera o valor `ngrams_pad`, então quando você executa
```
lm1.fit(ngrams_pad, vocab)
lm2.fit(ngrams_pad, vocab)
```
A segunda linha não vai funcionar, pois vai receber um `ngrams_pad` inválido.

A solução pra mim foi criar o `ngrams_pad` duas vezes :)

**Comment by Rian-Freitas** [comment]
Foi o que funcionou pra mim também!

Obrigado :3
